# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchReviewNEW():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchReviewNEW(self):
    self.driver.get("http://127.0.0.1:5000/landing")
    self.driver.set_window_size(1550, 926)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email-input").click()
    self.driver.find_element(By.ID, "email-input").send_keys("carol@example.com")
    self.driver.find_element(By.ID, "password-input").send_keys("carolpass")
    self.driver.find_element(By.ID, "password-input").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "My Stats").click()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("taco")
    self.driver.find_element(By.ID, "search-query").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "search-button").click()
    element = self.driver.find_element(By.ID, "search-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("sushi")
    self.driver.find_element(By.ID, "search-button").click()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("Spicy")
    self.driver.find_element(By.ID, "search-button").click()
    element = self.driver.find_element(By.ID, "search-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("Thai")
    self.driver.find_element(By.ID, "search-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "#search-results > .recommendation-card:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.LINK_TEXT, "OZfoody").click()
  
