"""Add seen to SharedPost

Revision ID: d111e4e089cf
Revises: eef2ea2ab1f3
Create Date: 2025-05-09 12:00:35.144463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd111e4e089cf'
down_revision = 'eef2ea2ab1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_post', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
