# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGlobePosts():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_globePosts(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(728, 886)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Global Stats").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(1) > g:nth-child(2) > g > g > g:nth-child(3) > g").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(1) > g > g:nth-child(3) > g > g > path").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(1) > g > g:nth-child(3) > g > g > path").click()
    self.driver.find_element(By.CSS_SELECTOR, "image").click()
    self.driver.find_element(By.CSS_SELECTOR, "image").click()
  
