# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateEditPost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createEditPost(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(728, 886)
    self.driver.find_element(By.CSS_SELECTOR, ".addPost").click()
    self.driver.find_element(By.ID, "Restaurant").click()
    self.driver.find_element(By.ID, "Restaurant").send_keys("Mcdonalds")
    self.driver.find_element(By.ID, "Cuisine").click()
    dropdown = self.driver.find_element(By.ID, "Cuisine")
    dropdown.find_element(By.XPATH, "//option[. = 'Italian']").click()
    self.driver.find_element(By.ID, "location").click()
    self.driver.find_element(By.ID, "location").send_keys("uwa")
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(2)").click()
    self.driver.find_element(By.ID, "Spiciness").send_keys("58")
    self.driver.find_element(By.ID, "Spiciness").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(8)").click()
    self.driver.find_element(By.ID, "Deliciousness").send_keys("42")
    self.driver.find_element(By.ID, "Deliciousness").click()
    element = self.driver.find_element(By.ID, "Value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "Value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "Value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "Value").send_keys("80")
    self.driver.find_element(By.ID, "Value").click()
    self.driver.find_element(By.ID, "Service").send_keys("28")
    self.driver.find_element(By.ID, "Service").click()
    self.driver.find_element(By.ID, "Review").click()
    self.driver.find_element(By.ID, "Review").send_keys("Good.")
    self.driver.find_element(By.ID, "images").click()
    self.driver.find_element(By.ID, "images").send_keys("C:\\fakepath\\Screenshot 2025-04-29 231442.png")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "Comment").click()
    self.driver.find_element(By.ID, "Comment").send_keys("Good")
    self.driver.find_element(By.ID, "Comment_button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-lg .btn-close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success").click()
    self.driver.find_element(By.ID, "recipientSearch").click()
    self.driver.find_element(By.ID, "recipientSearch").send_keys("James")
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item").click()
    self.driver.find_element(By.ID, "confirmShareBtn").click()
    element = self.driver.find_element(By.ID, "confirmShareBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-danger").click()
    self.driver.find_element(By.ID, "confirmDeletePostBtn").click()
  
