# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUpDuplicateEmail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUpDuplicateEmail(self):
    self.driver.get("http://127.0.0.1:5000/landing")
    self.driver.set_window_size(728, 886)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("James")
    self.driver.find_element(By.NAME, "email").send_keys("23722317@student.uwa.edu.au")
    self.driver.find_element(By.ID, "password").send_keys("Password1!")
    self.driver.find_element(By.ID, "eye-icon").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("Password1!")
    self.driver.find_element(By.ID, "eye-icon-confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, "#eye-icon > path").click()
    self.driver.find_element(By.CSS_SELECTOR, "#eye-icon-confirm > circle").click()
    self.driver.find_element(By.ID, "signupBtn").click()
  
