# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangeProfilePhoto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changeProfilePhoto(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(728, 886)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.ID, "profileImage").click()
    self.driver.find_element(By.ID, "profileImage").send_keys("C:\\fakepath\\Copy of Untitled graph.png")
    self.driver.find_element(By.CSS_SELECTOR, "#update-profile-form > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    element = self.driver.find_element(By.ID, "profileHeader")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "profileHeader")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "profileHeader")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "profileHeader").click()
    self.driver.find_element(By.ID, "profileHeader").click()
  
