# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logIn(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(728, 886)
    self.driver.find_element(By.LINK_TEXT, "OZfoody").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email-input").click()
    self.driver.find_element(By.ID, "email-input").send_keys("23722317@student.uwa.edu.au")
    self.driver.find_element(By.ID, "password-input").send_keys("Password1!")
    self.driver.find_element(By.ID, "password-input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    self.driver.find_element(By.LINK_TEXT, "My Stats").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Global Stats").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Inbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-fluid:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
