# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSharePost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sharePost(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(730, 886)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "Comment").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success").click()
    self.driver.find_element(By.ID, "recipientSearch").click()
    self.driver.find_element(By.ID, "recipientSearch").send_keys("James")
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item").click()
    self.driver.find_element(By.ID, "confirmShareBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#shareModal .btn-close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".reaction-buttons").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success").click()
    self.driver.find_element(By.ID, "recipientSearch").click()
    self.driver.find_element(By.ID, "recipientSearch").send_keys("Ian")
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item").click()
    self.driver.find_element(By.ID, "confirmShareBtn").click()
    element = self.driver.find_element(By.ID, "confirmShareBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
