# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendFriendRequest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sendFriendRequest(self):
    self.driver.get("http://127.0.0.1:5000/profile")
    self.driver.set_window_size(730, 886)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    self.driver.find_element(By.LINK_TEXT, "Friends").click()
    self.driver.find_element(By.ID, "search-input").click()
    self.driver.find_element(By.ID, "search-input").send_keys("Ian")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "View Profile").click()
    self.driver.find_element(By.ID, "follow-btn").click()
  
